# --------- aliases ----------
alias ll='ls -l'
alias la='ls -al'
alias latexmain='latexmk -pv -pvc -interaction=nonstopmode -pdf -pdflatex=lualatex -bibtex main.tex'
alias latexmainwithglossaries='latexmk -pv -pvc -interaction=nonstopmode -pdf -pdflatex="lualatex %S; makeglossaries main" -bibtex main.tex'
alias latexmkcleanalot='latexmk -CA; find . -name "*.bbl" -o -name "*.run.xml" -o -name "*.aux" | xargs rm'
alias work='$HOME/.work.sh'
alias vapdfs='impressive -T0 --fake-fullscreen *.pdf'
alias scrap='cd $HOME/.scraps; vim scrap.md'
alias pbc='xclip -selection clipboard'
alias clffiles='rm *.png *.pdf *.eps *.csv'
