;;; Compiled snippets and support files for `latex-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'latex-mode
		     '(("left| right|" "\\left|${1}\\right|" "||||" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/||||" nil nil)
		       ("left{ right}" "\\left{${1}\\right}" "{{}}" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/{{}}" nil nil)
		       ("zeta" "\\zeta" "zet" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/zet" nil nil)
		       ("xi" "\\xi" "xi" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/xi" nil nil)
		       ("widetilde" "\\widetilde{$1}$2" "wt" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/wt" nil nil)
		       ("vartheta" "\\vartheta" "vthe" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/vthe" nil nil)
		       ("varsigma" "\\varsigma" "vsig" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/vsig" nil nil)
		       ("varpho" "\\varrho" "vrho" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/vrho" nil nil)
		       ("varpi" "\\varpi" "vpi" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/vpi" nil nil)
		       ("varphi" "\\varphi" "vphi" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/vphi" nil nil)
		       ("varespilon" "\\varepsilon" "veps" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/veps" nil nil)
		       ("vec" "\\vec{$1}" "vec" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/vec" nil nil)
		       ("upsilon" "\\upsilon" "ups" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ups" nil nil)
		       ("up" "\\usepackage[${1:[options}]{${2:package}}" "up" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/up" nil nil)
		       ("ul" "\\underline{$1}" "ul" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ul" nil nil)
		       ("ub" "\\underbrace{$1}_{$2}" "ub" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ub" nil nil)
		       ("ts" "\\textsl{$1}" "ts" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ts" nil nil)
		       ("trace" "\\mathrm{tr}($1)" "tr" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/tr" nil nil)
		       ("times" "\\times " "times" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/times" nil nil)
		       ("ti" "\\textit{$1}" "ti" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ti" nil nil)
		       ("theta" "\\theta" "the" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/the" nil nil)
		       ("textstyle" "\\textstyle" "textstyle" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/textstyle" nil nil)
		       ("textcolor" "\\textcolor{red}{$2}" "textcolor" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/textcolor" nil nil)
		       ("text" "\\text{$1}$2" "text" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/text" nil nil)
		       ("tb" "\\textbf{$1}" "tb" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/tb" nil nil)
		       ("taylor" "\\mathrm{T}_{${1:(x,a)}} ${2:f(x)}" "tay" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/tay" nil nil)
		       ("tau" "\\tau" "tau" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/tau" nil nil)
		       ("tab" "\\begin{table}\n\\caption{${1:caption}}\n\\centering\n\\begin{tabular}{${2:c c}}\n\\toprule\n$ $3 $ & $ $4 $ \\\\\\\\\n\\midrule\na & b \\\\\\\\\nc & d \\\\\\\\\n\\bottomrule\n\\end{tabular}\n\\label{tab:${3:ex}}\n\\end{table}" "tab" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/tab" nil nil)
		       ("sum" "\\sum_{$1}^{$2}" "sum" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/sum" nil nil)
		       ("subsubsec" "\\subsubsection$1{$2}$0" "subsubsec" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/subsubsec" nil nil)
		       ("subsec" "\\subsection{$2}$0" "subsec" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/subsec" nil nil)
		       ("requires graphicx, floatrow, subfig packages" "\\begin{figure}\n  \\sidesubfloat[]{\\includegraphics{image1}\\label{fig:sub1}}\\\\\n  \\sidesubfloat[]{\\includegraphics{image2}\\label{fig:sub2}}%\n  \\caption{Two subfigures stacked, with one caption}\\label{fig:test}\n\\end{figure}" "subfigs_stacked_ig" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/subfigs_stacked_ig" nil nil)
		       ("sr" "\\stackrel{${1:top}}{$2}" "sr" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/sr" nil nil)
		       ("sqrt" "\\sqrt{$1}" "sqrt" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/sqrt" nil nil)
		       ("snote" "\\snote{$1}$2" "snote" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/snote" nil nil)
		       ("setminus" "\\setminus $1" "sm" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/sm" nil nil)
		       ("slashed, requires *slashed* package" "\\slashed{$1}" "sl" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/sl" nil nil)
		       ("sigma" "\\sigma" "sig" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/sig" nil nil)
		       ("si siunitx" "\\si{$1}" "si" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/si" nil nil)
		       ("sec" "\\section$1{$2}$0" "sec" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/sec" nil nil)
		       ("same" "\\same" "same" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/same" nil nil)
		       ("rho" "\\rho" "rho" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/rho" nil nil)
		       ("rev" "\\mathrm{rev}" "rev" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/rev" nil nil)
		       ("ref" "~\\ref{$1:$2} $3" "ref" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ref" nil nil)
		       ("ref equation" "~\\ref{eq:$1} $2" "reeq" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/reeq" nil nil)
		       ("rarr" "\\rightarrow" "rarr" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/rarr" nil nil)
		       ("qd" "\\quad" "qd" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/qd" nil nil)
		       ("psi" "\\psi" "psi" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/psi" nil nil)
		       ("pi" "\\pi" "pi" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/pi" nil nil)
		       ("phi" "\\phi" "phi" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/phi" nil nil)
		       ("perp" "\\perp" "perp" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/perp" nil nil)
		       ("pdvt" "\\left( \\pdv{$1}{$2} \\right)_{$3}" "pdvt" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/pdvt" nil nil)
		       ("pdv" "\\pdv{$1}{$2}" "pdv" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/pdv" nil nil)
		       ("omega" "\\omega" "ome" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ome" nil nil)
		       ("ol" "\\overline{$1}" "ol" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ol" nil nil)
		       ("oint" "\\oint_{$1}^{$2}" "oint" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/oint" nil nil)
		       ("ob" "\\overbrace{$1}^{$2}" "ob" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ob" nil nil)
		       ("new main glossary entry" "\\newglossaryentry{$1}{name={$1}, description={$3}}" "nw" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/nw" nil nil)
		       ("num siunitx" "\\num{$1}" "num" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/num" nil nil)
		       ("nu" "\\nu" "nu" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/nu" nil nil)
		       ("new symbol" "\\newglossaryentry{$1}{name={$2}, description={$3}, type=symbolslist}" "ns" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ns" nil nil)
		       ("numerische Parameter" "\\bar{n}_{ i_\\mathrm{max}} = \\num{$1}, i_\\mathrm{max} = $2" "np" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/np" nil nil)
		       ("new_main_takeaway" "\\newglossaryentry{$1}{name={$2}, description={$3}, type=maintakeawayslist}" "nmt" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/nmt" nil nil)
		       ("new_figure_explanation" "\\newglossaryentry{$1}{name={$2}, description={$3}, type=figureexplanationslist}" "nfe" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/nfe" nil nil)
		       ("nc-snote" "\\newcommand{\\snote}[1]{{\\scriptsize \\textbf{#1} }}" "nc-snote" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/nc-snote" nil nil)
		       ("nc-ceilfloor" "\\DeclarePairedDelimiter\\ceil{\\lceil}{\\rceil}\n\\DeclarePairedDelimiter\\floor{\\lfloor}{\\rfloor}" "nc-ceilfloor" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/nc-ceilfloor" nil nil)
		       ("newcommand-Rdot" "\\newcommand{\\Rdot}{R^{\\bullet}}" "nc-Rdot" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/nc-Rdot" nil nil)
		       ("newcommand-Pdot" "\\newcommand{\\Pdot}{P^{\\bullet}}" "nc-Pdot" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/nc-Pdot" nil nil)
		       ("nbar_imax" "\\bar{n}_{ i_\\mathrm{max}}" "nbim" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/nbim" nil nil)
		       ("nab" "\\nabla" "nabla" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/nabla" nil nil)
		       ("new acronym" "\\newglossaryentry{$1}{name={$2}, description={$3}, type=\\acronymtype}" "na" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/na" nil nil)
		       ("mu" "\\mu" "mu" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/mu" nil nil)
		       ("mrm" "\\mathrm{$1}" "mrm" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/mrm" nil nil)
		       ("mkbs" "\\makebox[\\textwidth][c]{\\scalebox{1.0}{\\input{${1:fig.pgf}}}}" "mkbs" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/mkbs" nil nil)
		       ("mbb" "\\mathbb{$1}" "mbb" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/mbb" nil nil)
		       ("mapsto" "\\mapsto" "mapsto" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/mapsto" nil nil)
		       ("lrarr" "\\leftrightarrow" "lrarr" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/lrarr" nil nil)
		       ("lra" "\\langle $1 \\rangle" "lra" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/lra" nil nil)
		       ("ln" "\\ln" "ln" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ln" nil nil)
		       ("ldots" "\\ldots" "ld" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ld" nil nil)
		       ("lambda" "\\lambda" "lam" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/lam" nil nil)
		       ("label equation" "\\label{eq:$1} $2" "laeq" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/laeq" nil nil)
		       ("label" "\\label{$1:$2} $3" "label" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/label" nil nil)
		       ("rational numbers" "\\mathbb{N}" "lR" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/lR" nil nil)
		       ("natural numbers with 0" "\\mathbb{N}" "lN0" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/lN0" nil nil)
		       ("natural numbers" "\\mathbb{N}" "lN" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/lN" nil nil)
		       ("ket" "\\ket{$1}$0" "ket" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ket" nil nil)
		       ("kappa" "\\kappa" "kap" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/kap" nil nil)
		       ("item" "\\item" "it" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/it" nil nil)
		       ("iota" "\\iota" "iot" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/iot" nil nil)
		       ("int" "\\int_{$1}^{$2}" "int" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/int" nil nil)
		       ("inf" "\\infinity" "inf" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/inf" nil nil)
		       ("imp" "\\implies" "imp" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/imp" nil nil)
		       ("imax" "i_\\mathrm{max}" "imax" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/imax" nil nil)
		       ("dollars" "\\$ $1\\$$2" "ii" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ii" nil nil)
		       ("igtw" "\\includegraphics[width=0.5\\textwidth]{$1}" "igtw" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/igtw" nil nil)
		       ("ig" "\\includegraphics[${1:scale=0.6}]{$2}" "ig" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ig" nil nil)
		       ("horizontal line" "\\\\ \\\\\\\\ \\noindent\\rule{\\textwidth}{1pt}" "hrule" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/hrule" nil nil)
		       ("hb" "\\hbar" "hb" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/hb" nil nil)
		       ("hat" "\\hat{$1}$0" "hat" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/hat" nil nil)
		       ("glossary entry occurrence" "\\gls{$1}" "gls" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/gls" nil nil)
		       ("gamma" "\\gamma" "gam" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/gam" nil nil)
		       ("ft" "\\begin{tcolorbox} \n\\textbf{$1:} \\textit{$2}\n\\begin{equation*}\n$3\n\\end{equation*}\n\\end{tcolorbox}" "fundamental theorem" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/fundamental_theorem" nil nil)
		       ("figures side by side" "\\begin{table}\n\\centering\n\\begin{minipage}{.5\\textwidth}\n\\centering\n\\includegraphics[width=.4\\linewidth]{blacksquare.png}\n\\captionof{figure}{A figure}\n\\label{fig:test1}\n\\end{minipage}%\n\\begin{minipage}{.5\\textwidth}\n\\centering\n\\includegraphics[width=.4\\linewidth]{blacksquare.png}\n\\captionof{figure}{Another figure}\n\\label{fig:test2}\n\\end{minipage}\n\\end{table}" "fsbs" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/fsbs" nil nil)
		       ("fr" "\\frac{$1}{$2}" "fr" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/fr" nil nil)
		       ("fn" "\\footnotetext{$1}" "fn" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/fn" nil nil)
		       ("fl" "\\flat" "fl" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/fl" nil nil)
		       ("fig" "\\begin{figure}\n\\centering\n\\includegraphics[width=0.5\\textwidth]{$1}\n\\caption{${2:caption}}\n\\label{fig:${1:ex}}\n\\end{figure}" "fig" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/fig" nil nil)
		       ("fg" "\\fg{$1}{$2}" "fg" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/fg" nil nil)
		       ("forall" "\\forall $1" "fa" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/fa" nil nil)
		       ("eta" "\\eta" "eta" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/eta" nil nil)
		       ("equation split env" "\\begin{equation}\n\\begin{split}\n$1\n\\end{split}\n\\end{equation}\n$0" "eqs" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/eqs" nil nil)
		       ("eps_tex" "\\documentclass{standalone}\n\\usepackage{amsmath,amssymb}\n\\usepackage{graphicx, xcolor}\n\\begin{document}\n\\input{$1.eps_tex}\n\\end{document}" "eps_tex" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/eps_tex" nil nil)
		       ("epsilon" "\\epsilon" "eps" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/eps" nil nil)
		       ("enquote" "\\enquote{$1}" "enq" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/enq" nil nil)
		       ("dv" "\\dv{$1}{$2}" "dv" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/dv" nil nil)
		       ("dots" "\\dots" "dots" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/dots" nil nil)
		       ("dot" "\\dot{$1}" "dot" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/dot" nil nil)
		       ("determinant" "\\det " "det" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/det" nil nil)
		       ("delta" "\\delta" "del" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/del" nil nil)
		       ("ddot" "\\ddot{$1}" "ddot" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ddot" nil nil)
		       ("dd" "\\dd{$1}" "dd" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/dd" nil nil)
		       ("datemark" "\\newline \\hspace*{-3.3cm}\\textbf{$1} \\newline $0" "datemark" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/datemark" nil nil)
		       ("dag" "\\dag" "dag" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/dag" nil nil)
		       ("cref" "\\cref{$1:$2}$3" "cref" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/cref" nil nil)
		       ("centered pgf" "\\begin{figure}\n\\makebox[\\textwidth][c]{\\input{${1:fig.pgf}}}\n\\caption{caption}\n\\label{fig:ex}\n\\end{figure}" "cpgf" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/cpgf" nil nil)
		       ("corr" "\\corr{$1}" "corr" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/corr" nil nil)
		       ("const" "\\mathrm{const}" "const" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/const" nil nil)
		       ("comma (Komma) nach Gleichung" "\\quad ," "com" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/com" nil nil)
		       ("column" "\\column{0.5\\textwidth}" "column" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/column" nil nil)
		       ("cmax2" "c_{\\mathrm{max,2}}" "cmax2" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/cmax2" nil nil)
		       ("child_node" "child { node {$1} \n}" "chno" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/chno" nil nil)
		       ("childf" "child {\n  g[]{$1}\n  p[]{$2}\n}" "childf" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/childf" nil nil)
		       ("child" "c[]{$1}" "child" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/child" nil nil)
		       ("chi" "\\chi" "chi" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/chi" nil nil)
		       ("cdot" "\\cdot" "cdot" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/cdot" nil nil)
		       ("cd" "\\cdot" "cd" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/cd" nil nil)
		       ("chord" "\\cc{$1}{$2}{$3}{$4}" "cc" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/cc" nil nil)
		       ("cb" "\\cb{$1}{$2}{$3}" "cb" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/cb" nil nil)
		       ("bu" "\\bullet" "bu" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/bu" nil nil)
		       ("braket" "\\braket{$1}{$2}$0" "braket" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/braket" nil nil)
		       ("bra" "\\bra{$1}$0" "bra" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/bra" nil nil)
		       ("bauplan" "{\\tiny \\shortstack{$1}}" "bp" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/bp" nil nil)
		       ("big old" "{\\Large \\textbf{$1} \\hspace*{10pt}} " "bigol" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/bigol" nil nil)
		       ("bi" "\\binom{$1}{$2}" "bi" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/bi" nil nil)
		       ("beta" "\\beta" "bet" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/bet" nil nil)
		       ("begit" "\\begin{itemize}\n\\item $0\n\\end{itemize}" "begit" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/begit" nil nil)
		       ("beg" "\\begin{${1:some env}}\n$0\n\\end{$1}" "beg" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/beg" nil nil)
		       ("bbs" "\\left[ $1 \\right]" "bbs" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/bbs" nil nil)
		       ("bbn" "\\left( $1 \\right)" "bbn" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/bbn" nil nil)
		       ("bbc" "\\left\\\\{ $1 \\right\\\\}" "bbc" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/bbc" nil nil)
		       ("bba" "\\left\\langle $1 \\right\\rangle" "bba" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/bba" nil nil)
		       ("bar" "\\bar{$1}" "bar" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/bar" nil nil)
		       ("ana" "\\ana{$1}{$2}" "ana" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ana" nil nil)
		       ("alpha" "\\alpha" "alp" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/alp" nil nil)
		       ("ala" "\\begin{alignat${1:*}}{1}\n$2&= \\\\\\\n&=\n\\end{alignat$1}" "ala" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/ala" nil nil)
		       ("_" "_{$1}" "_" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/_" nil nil)
		       ("^" "^{$1}" "^" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/^" nil nil)
		       ("left[ right]" "\\left[${1}\\right]" "[[]]" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/[[]]" nil nil)
		       ("Zeta" "\\Zeta" "Zet" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Zet" nil nil)
		       ("Xi" "\\Xi" "Xi" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Xi" nil nil)
		       ("Upsilon" "\\Upsilon" "Ups" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Ups" nil nil)
		       ("Theta" "\\Theta" "The" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/The" nil nil)
		       ("Tau" "\\Tau" "Tau" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Tau" nil nil)
		       ("Student" "\\Student{$1}" "Student" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Student" nil nil)
		       ("Sigma" "\\Sigma" "Sig" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Sig" nil nil)
		       ("SI" "\\SI{$1}{$2}" "SI" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/SI" nil nil)
		       ("Rho" "\\Rho" "Rho" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Rho" nil nil)
		       ("Rdot" "R_{$1}^\\bullet$0" "Rdot" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Rdot" nil nil)
		       ("Psi" "\\Psi" "Psi" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Psi" nil nil)
		       ("Pi" "\\Pi" "Pi" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Pi" nil nil)
		       ("Phi" "\\Phi" "Phi" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Phi" nil nil)
		       ("PDI" "$\\mathrm{PDI}$" "PDI" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/PDI" nil nil)
		       ("Omega" "\\Omega" "Ome" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Ome" nil nil)
		       ("Nu" "\\Nu" "Nu" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Nu" nil nil)
		       ("Ndot" "N_{$1}^\\bullet$0" "Ndot" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Ndot" nil nil)
		       ("Mu" "\\Mu" "Mu" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Mu" nil nil)
		       ("Lrarr" "\\Leftrightarrow" "Lrarr" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Lrarr" nil nil)
		       ("Lambda" "\\Lambda" "Lam" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Lam" nil nil)
		       ("Kappa" "\\Kappa" "Kap" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Kap" nil nil)
		       ("Iota" "\\Iota" "Iot" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Iot" nil nil)
		       ("Gamma" "\\Gamma" "Gam" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Gam" nil nil)
		       ("Frage" "\\Frage{$1}" "Frage" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Frage" nil nil)
		       ("Eta" "\\Eta" "Eta" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Eta" nil nil)
		       ("Epsilon" "\\Epsilon" "Eps" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Eps" nil nil)
		       ("Delta" "\\Delta" "Del" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Del" nil nil)
		       ("Chi" "\\Chi" "Chi" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Chi" nil nil)
		       ("Beta" "\\Beta" "Bet" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Bet" nil nil)
		       ("Alpha" "\\Alpha" "Alp" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/Alp" nil nil)
		       ("left( right)" "\\left(${1}\\right)" "(())" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/(())" nil nil)
		       ("code_folding" "%{{{ $1\n%}}}" "%{" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/%{" nil nil)
		       ("sharp" "\\sharp" "#" nil nil nil "/home/chris/.emacs.d/snippets/latex-mode/#" nil nil)))


;;; Do not edit! File generated at Fri Mar  8 09:49:12 2019
